# Generated by Django 3.1.7 on 2021-04-03 10:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('dept_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('contact_no', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='doctors',
            fields=[
                ('doc_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('doc_gender', models.CharField(max_length=1)),
                ('contact', models.CharField(max_length=10)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.department')),
            ],
        ),
        migrations.CreateModel(
            name='nurses',
            fields=[
                ('nur_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('n_gender', models.CharField(max_length=1)),
                ('contact', models.CharField(max_length=10)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.department')),
            ],
        ),
        migrations.CreateModel(
            name='patients',
            fields=[
                ('pat_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=1)),
                ('contact', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('password', models.CharField(max_length=20)),
                ('confirm_password', models.CharField(max_length=20)),
                ('last_login', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='patientStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(default=None, max_length=100)),
                ('nurse_name', models.CharField(default=None, max_length=100)),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.doctors')),
                ('nur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.nurses')),
                ('pat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.patients')),
            ],
        ),
    ]
